### ISSUE TITLE
Fire Bombs (from bombos)

### ISSUE THREAD

**Issue by Cavin856** [spannerisms/Globular#2]
Press X for Bombos to create a fire bomb where link is currently standing.
This fire bomb explodes after a short period of time, 
This bomb can be moved by conveyors (like the Somaria block) and when it explodes, a fireball (like the ones from Fire Rod) is shot out in each of the 4 cardinal directions (like the Somaria block again)
Creating a fire bomb uses 1/4 of your standard magic bar.

**Comment by spannerisms** [comment]
I'm a bit wary about having 4 ancillae initialized at once, but this should be doable.
